### PR TITLE
implemented Selector.getVueXXX (close #8)

### LINKED ISSUE #8: [New API] VueSelector.getVueProperty
`VueSelector.getVue()`

### PR DESCRIPTION
**Pull request by miherlosev**
@kirovboris
Before publish module to npm I will update testcafe to the latest stable version

### CODE REVIEW

**Comment by kirovboris** [comment]
Depth-first search is slower than [`treeWalker`](https://developer.mozilla.org/ru/docs/Web/API/Document/createTreeWalker)
E.g. you can see perfomance comparison here:
https://jsperf.com/createnodeiterator-vs-createtreewalker-vs-getelementsby

**Comment by kirovboris** [comment]
For getting state and props of React component we implemented the following mechanism:
```js
var reactComponent = await ReactSelector('Component').getReact();
var myProp         = reactComponent.props.myProp;

//OR

var myProp = await ReactSelector('Component').getReact(({props, state}) => {
    return props.myProp;
});
```

I suggest add the similar mechnism here.

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
FPR

**Pull request merged**
